
# SEO settings
title: "Do you even blog bro?"
#title2: "/blog" # default: ""
#description: "Just another minimalist Jekyll theme for technical writing."
#keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://blackeagle01.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "hnbloggithub"
#twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Harsh Tiku"
  job      : "student at NIT Hamirpur"
  bio      : " I'm just a Keen learner trying to make this world a better place.Check out my blog"
  thumb    : /images/author.jpg
  email    : tiku.harsh@gmail.com
  url      : http://blackeagle.github.io
  
# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
